# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-28-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/Github-Kotlin---Kanamobi-Android

    environment:
          JVM_OPTS: -Xmx3200m
          CIRCLE_JDK_VERSION: oraclejdk8

        steps:
          - checkout

          - restore_cache:
              key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

          - run:
              name: Accept licenses
              command: yes | sdkmanager --licenses || true

          - run:
              name: Build
              command: ./gradlew clean check build assembleAndroidTest

          - save_cache:
              paths:
                - ~/.gradle
              key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}


