version: 2
jobs:
  build:
    working_directory: ~/Github-Kotlin---Kanamobi-Android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      CIRCLE_JDK_VERSION: oraclejdk8
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Create release key
          command: echo $DECRYPT_KEY | base64 --decode >> ${HOME}/distribution/release.keystore
      - run:
          name: Decrypt release key
          command: echo 'export KEYSTORE_PATH=${HOME}/distribution/release.keystore' >> $BASH_ENV
      - run:
          name: Build
          command: ./gradlew clean check build assembleAndroidTest
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
